version: "3"

services:
  server:
    image: abiosoft/caddy
    volumes:
      - Caddyfile:/etc/Caddyfile
      - ~/.caddy:/root/.caddy
    ports:
      - "80:80"
      - "443:443"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ageobot
    env_file:
        - .env
    volumes:
      - .:/app
    ports:
      - "8080:80"
    networks:
      - defaultnetwork
    user: $UID:$GID

networks:
    defaultnetwork:
        driver: bridge